name: Staging the app

on: 
  pull_request:
    types: [labeled]
    
env:
  DOCKER_IMAGE_NAME: Elias-Vandewalle-azure-ttt
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  #################################################
  ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
  #################################################
  #################################################
  ### REPLACE USERNAME WITH GH USERNAME         ###
  AZURE_WEBAPP_NAME: Elias-Vandewalle-ttt-app
  #################################################

jobs:
  build:
    runs-on: ubuntu-latest
